"""
AI Interface - This is where you'll integrate your AI agent

This abstract class defines the interface between the backend and your AI system.
Replace the mock implementations with your actual AI logic.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any, Literal
from datetime import datetime

from pydantic import BaseModel, Field, constr, validator


SeverityLiteral = Literal["critical", "high", "medium", "low", "info"]


class PlanStep(BaseModel):
    """Single step the agent should execute."""

    command: constr(strip_whitespace=True, min_length=1)
    description: constr(strip_whitespace=True, min_length=1)
    rationale: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ExecutionLogEntry(BaseModel):
    """Structured execution log used throughout the dashboard."""

    level: Literal["debug", "info", "success", "warning", "error"]
    component: constr(strip_whitespace=True, min_length=1)
    message: constr(strip_whitespace=True, min_length=1)
    details: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PortDiscovery(BaseModel):
    """Discovered network port."""

    host: constr(strip_whitespace=True, min_length=1)
    port: int = Field(..., ge=1, le=65535)
    service: constr(strip_whitespace=True, min_length=1)
    version: Optional[str] = None


class ServiceIdentification(BaseModel):
    """Identified service banner or metadata."""

    host: constr(strip_whitespace=True, min_length=1)
    service: constr(strip_whitespace=True, min_length=1)
    banner: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class VulnerabilityFinding(BaseModel):
    """Finding returned by the agent's analysis pipeline."""

    cve: constr(pattern=r"^CVE-\\d{4}-\\d{4,7}$")
    title: constr(strip_whitespace=True, min_length=1)
    severity: SeverityLiteral
    cvss: Optional[float] = Field(default=None, ge=0.0, le=10.0)
    target: constr(strip_whitespace=True, min_length=1)
    port: constr(strip_whitespace=True, min_length=1)
    service: Optional[str] = None
    description: Optional[str] = None
    remediation: Optional[str] = None
    exploit_available: bool = False
    references: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @validator("references", each_item=True)
    def _strip_reference(cls, value: str) -> str:  # noqa: D401
        """Ensure reference entries are clean strings."""

        return value.strip()


class AttackPlan(BaseModel):
    """Attack plan generated by AI"""
    target: constr(strip_whitespace=True, min_length=1)
    steps: List[PlanStep]
    reasoning: constr(strip_whitespace=True, min_length=1)
    estimated_duration: constr(strip_whitespace=True, min_length=1)


class ScanResult(BaseModel):
    """Scan results from AI execution"""
    hosts_discovered: List[constr(strip_whitespace=True, min_length=1)]
    ports_discovered: List[PortDiscovery]
    services_identified: List[ServiceIdentification]
    vulnerabilities_found: List[VulnerabilityFinding]
    execution_logs: List[ExecutionLogEntry]


class SelfHealError(RuntimeError):
    """Raised when the AI cannot produce a viable heal script."""


class GraphSyncError(RuntimeError):
    """Raised when graph persistence fails."""


class AIInterface(ABC):
    """
    Abstract interface for AI integration
    
    IMPLEMENTATION GUIDE:
    1. Create a new class that inherits from AIInterface
    2. Implement all abstract methods with your AI logic
    3. Replace the DummyAI implementation in scan_service.py
    
    Example:
        class MyTrinityAI(AIInterface):
            def __init__(self, llm_model: str):
                self.llm = load_your_llm(llm_model)
                
            async def generate_attack_plan(self, target, config):
                # Your LLM-based planning logic
                plan = self.llm.generate(...)
                return plan
    """
    
    @abstractmethod
    async def generate_attack_plan(
        self,
        target: str,
        scan_profile: str,
        config: Dict[str, Any]
    ) -> AttackPlan:
        """
        Generate an attack plan for the target using LLM
        
        Args:
            target: Target IP/subnet (e.g., "192.168.1.0/24")
            scan_profile: Scan profile ("quick", "full", "stealth", "web")
            config: Additional configuration options
            
        Returns:
            AttackPlan object with steps and reasoning
        """
        pass
    
    @abstractmethod
    async def execute_scan(
        self,
        attack_plan: AttackPlan,
        config: Dict[str, Any]
    ) -> ScanResult:
        """
        Execute the attack plan and return results
        
        This is where your agent executes commands, handles failures,
        and uses self-healing mechanisms.
        
        Args:
            attack_plan: The generated attack plan
            config: Execution configuration (timeouts, retries, etc.)
            
        Returns:
            ScanResult with discovered hosts, ports, services, and vulnerabilities
        """
        pass
    
    @abstractmethod
    async def self_heal_script(
        self,
        failed_script: str,
        error_message: str,
        context: Dict[str, Any]
    ) -> str:
        """
        Use LLM to rewrite a failed script with a new approach
        
        Args:
            failed_script: The script that failed
            error_message: Error message from execution
            context: Additional context about the failure
            
        Returns:
            Rewritten script as string. Implementations should raise ``SelfHealError``
            when a viable patch cannot be generated so the caller can abort safely.
        """
        pass
    
    @abstractmethod
    async def analyze_vulnerability(
        self,
        service_info: Dict[str, Any],
        use_rag: bool = True
    ) -> List[Dict[str, Any]]:
        """
        Analyze service information and identify vulnerabilities
        
        Uses RAG (ChromaDB) for CVE similarity search if enabled.
        
        Args:
            service_info: Information about the discovered service
            use_rag: Whether to use RAG for CVE lookup
            
        Returns:
            List of potential vulnerabilities
        """
        pass
    
    @abstractmethod
    async def update_graph(
        self,
        scan_result: ScanResult,
        scan_id: str
    ) -> bool:
        """
        Update Neo4j graph with scan results
        
        Creates nodes for hosts, ports, services, CVEs and their relationships.
        Expected mapping:
            - Host IP -> ``Host`` node
            - Port discovery -> ``Port`` node linked via ``HAS_PORT``
            - Service identification -> ``RUNS_SERVICE`` relationship
            - Vulnerability finding -> ``CVE`` node linked via ``VULNERABLE_TO``
        
        Args:
            scan_result: Results from scan execution
            scan_id: Unique scan identifier
            
        Returns:
            True if successful. Implementations should raise ``GraphSyncError``
            when persistence fails so the caller can surface actionable logs.
        """
        pass


# ============= DUMMY IMPLEMENTATION (REPLACE THIS WITH YOUR AI) =============

class DummyAI(AIInterface):
    """
    Mock AI implementation for testing
    
    ⚠️ REPLACE THIS WITH YOUR ACTUAL AI IMPLEMENTATION ⚠️
    
    This provides realistic fake data so the frontend works
    while you develop your actual AI agent.
    """
    
    def __init__(self, llm_model: str = "llama3.1:8b-instruct"):
        self.llm_model = llm_model
        print(f"🤖 DummyAI initialized with model: {llm_model}")
        print("⚠️  This is a MOCK implementation - replace with your actual AI!")
    
    async def generate_attack_plan(
        self,
        target: str,
        scan_profile: str,
        config: Dict[str, Any]
    ) -> AttackPlan:
        """Mock attack plan generation"""
        
        # Simulate different plans based on profile
        if scan_profile == "quick":
            steps = [
                PlanStep(command=f"nmap -sn {target}", description="Host discovery"),
                PlanStep(command=f"nmap -sV -T4 {target}", description="Service detection"),
            ]
            duration = "~5 minutes"
        elif scan_profile == "full":
            steps = [
                PlanStep(command=f"nmap -sn {target}", description="Host discovery"),
                PlanStep(command=f"nmap -sS -sV -A {target}", description="Full port scan"),
                PlanStep(command=f"nmap -sC --script vuln {target}", description="Vulnerability scan"),
            ]
            duration = "~30 minutes"
        else:
            steps = [
                PlanStep(command=f"nmap -sn {target}", description="Host discovery"),
            ]
            duration = "~10 minutes"
        
        return AttackPlan(
            target=target,
            steps=steps,
            reasoning=f"Generated {scan_profile} scan plan for {target} using {self.llm_model}",
            estimated_duration=duration
        )
    
    async def execute_scan(
        self,
        attack_plan: AttackPlan,
        config: Dict[str, Any]
    ) -> ScanResult:
        """Mock scan execution"""
        
        # Return realistic mock data
        return ScanResult(
            hosts_discovered=["192.168.1.1", "192.168.1.42", "192.168.1.105"],
            ports_discovered=[
                PortDiscovery(host="192.168.1.42", port=22, service="SSH", version="OpenSSH 8.2"),
                PortDiscovery(host="192.168.1.42", port=80, service="HTTP", version="Apache 2.4.41"),
                PortDiscovery(host="192.168.1.105", port=443, service="HTTPS", version="nginx 1.18"),
                PortDiscovery(host="192.168.1.105", port=3306, service="MySQL", version="MySQL 8.0.23"),
            ],
            services_identified=[
                ServiceIdentification(host="192.168.1.42", service="SSH", banner="OpenSSH_8.2p1"),
                ServiceIdentification(host="192.168.1.105", service="HTTPS", banner="nginx/1.18.0"),
            ],
            vulnerabilities_found=[
                VulnerabilityFinding(
                    cve="CVE-2024-3094",
                    title="XZ Utils Backdoor",
                    severity="critical",
                    cvss=10.0,
                    target="192.168.1.42",
                    port="22",
                    service="SSH",
                    description="Malicious code in XZ Utils liblzma library",
                ),
                VulnerabilityFinding(
                    cve="CVE-2023-44487",
                    title="HTTP/2 Rapid Reset Attack",
                    severity="high",
                    cvss=7.5,
                    target="192.168.1.105",
                    port="443",
                    service="HTTPS",
                    description="HTTP/2 protocol vulnerability",
                ),
            ],
            execution_logs=[
                ExecutionLogEntry(level="info", component="Planner", message=f"Generated attack plan for {attack_plan.target}"),
                ExecutionLogEntry(level="success", component="Executor", message="Scan completed successfully"),
            ],
        )
    
    async def self_heal_script(
        self,
        failed_script: str,
        error_message: str,
        context: Dict[str, Any]
    ) -> str:
        """Mock self-healing"""
        return f"# Healed version of script\n{failed_script}\n# Added error handling for: {error_message}"
    
    async def analyze_vulnerability(
        self,
        service_info: Dict[str, Any],
        use_rag: bool = True
    ) -> List[Dict[str, Any]]:
        """Mock vulnerability analysis"""
        return [
            {
                "cve": "CVE-2024-1234",
                "confidence": 0.85,
                "source": "ChromaDB RAG" if use_rag else "Direct lookup"
            }
        ]
    
    async def update_graph(
        self,
        scan_result: ScanResult,
        scan_id: str
    ) -> bool:
        """Mock graph update"""
        print(f"📊 Would update Neo4j graph for scan {scan_id}")
        print(f"   - Hosts: {len(scan_result.hosts_discovered)}")
        print(f"   - Ports: {len(scan_result.ports_discovered)}")
        print(f"   - Vulnerabilities: {len(scan_result.vulnerabilities_found)}")
        return True
